name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - master  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # 최신 Ubuntu 버전에서 실행

    steps:
      # Git 체크아웃
    - name: Checkout code
      uses: actions/checkout@v2

      # Java 및 Maven 설정
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

      # 의존성 설치 및 빌드
    - name: Build Spring Boot App
      run: |
        ./mvnw clean package -DskipTests

      # sshpass 설치
    - name: Install sshpass
      run: sudo apt-get install -y sshpass

      # 원격 서버에 디렉토리 생성
    - name: Deploy to Server - Create Directory
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 50 admin@${{ secrets.HOST }} "mkdir -p /opt/springboot"

      # 빌드한 .jar 파일을 원격 서버로 전송
    - name: Deploy to Server - Copy JAR File
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no -P 50 target/*.jar admin@${{ secrets.HOST }}:/opt/springboot/app.jar

      # 기존 프로세스 종료 및 애플리케이션 실행
    - name: Deploy to Server - Restart Application
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 50 admin@${{ secrets.HOST }} "
        pkill -f 'java -jar' || echo 'No existing process to kill';
        nohup java -jar /opt/springboot/app.jar > /opt/springboot/app.log 2>&1 &"
