name: Build, Deploy and Run Spring Boot App

on:
  push:
    branches:
      - master  # main 브랜치에 푸시될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle Wrapper 실행 권한 부여
      - name: Ensure Gradle Wrapper is executable
        run: chmod +x gradlew

      # 환경 변수 파일 생성
      - name: Create Application yml
        run: echo "${{ secrets.YML }}" > src/main/resources/application.yml
        
      # 환경 변수 파일 생성
      - name: Create Application Properties
        run: echo "${{ secrets.PROPERTIES }}" > src/main/resources/application.properties

      # 4. 애플리케이션 빌드
      - name: Build Spring Boot App
        run: ./gradlew clean build -x test

      # 5. sshpass 설치
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # 6. 원격 서버에 디렉토리 생성
      - name: Deploy to Server - Create Directory
        run: |
            sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 50 admin@${{ secrets.HOST }} "echo '${{ secrets.PASSWORD }}' | sudo -S mkdir -p /home/admin/springboot/"
            
      # 7. 기존 애플리케이션 종료 및 새 JAR 실행
      - name: Restart and Run Application
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 50 admin@${{ secrets.HOST }} "
          /home/admin/springboot/stop_app.sh;
          /home/admin/springboot/start_app.sh;"

      # 8. 애플리케이션 상태 확인
      - name: Check Application Status
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no -p 50 admin@${{ secrets.HOST }} "
          sleep 5; # 애플리케이션 실행 대기
          ps aux | grep 'java -jar /home/admin/springboot/app.jar/caselist-0.0.1-SNAPSHOT.jar'"
